version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: health
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: health
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  db-data: null
