# Generated by Django 4.2.6 on 2023-10-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.CharField(max_length=10, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужчина"), ("F", "Женщина")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration",
            field=models.CharField(max_length=50, verbose_name="Регистрация"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="surname",
            field=models.CharField(max_length=20, verbose_name="Отчество"),
        ),
    ]
